# Generated by Django 3.2 on 2024-08-24 14:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Content_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/images/')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressiveBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=50)),
                ('amount_1', models.IntegerField()),
                ('title_2', models.CharField(max_length=50)),
                ('amount_2', models.IntegerField()),
                ('title_3', models.CharField(max_length=50)),
                ('amount_3', models.IntegerField()),
                ('title_4', models.CharField(max_length=50)),
                ('amount_4', models.IntegerField()),
                ('title_5', models.CharField(max_length=50)),
                ('amount_5', models.IntegerField()),
                ('title_6', models.CharField(max_length=50)),
                ('amount_6', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('video_link', models.URLField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('approch', 'Approch'), ('impact', 'Impact'), ('general', 'General')], default='general', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_content_image', to='BackendAPIs.imagelibrary')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opptional_dasboard', models.CharField(blank=True, max_length=200, unique=True)),
                ('activate_dasboard', models.BooleanField(blank=True, default=False)),
                ('responsible_emails', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_motivation_text1', models.TextField()),
                ('page_motivation_text2', models.TextField()),
                ('related_information', models.TextField()),
                ('embedded_links1', models.URLField(blank=True, null=True)),
                ('embedded_links2', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_gallery1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_content_gallery1', to='BackendAPIs.content_gallery')),
                ('content_gallery2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_content_gallery2', to='BackendAPIs.content_gallery')),
                ('content_gallery3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_content_gallery3', to='BackendAPIs.content_gallery')),
                ('content_gallery4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_content_gallery4', to='BackendAPIs.content_gallery')),
                ('content_gallery5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_content_gallery5', to='BackendAPIs.content_gallery')),
                ('content_gallery6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_content_gallery6', to='BackendAPIs.content_gallery')),
                ('project_approach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_approach', to='BackendAPIs.projectcontent')),
                ('project_content1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_content_1', to='BackendAPIs.projectcontent')),
                ('project_content2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_content_2', to='BackendAPIs.projectcontent')),
                ('project_content3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_content_3', to='BackendAPIs.projectcontent')),
                ('project_content4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_content_4', to='BackendAPIs.projectcontent')),
                ('project_content5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_content_5', to='BackendAPIs.projectcontent')),
                ('project_content6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_content_6', to='BackendAPIs.projectcontent')),
                ('project_impact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_impact', to='BackendAPIs.projectcontent')),
                ('project_progressive_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_progressive_bar', to='BackendAPIs.progressivebar')),
                ('project_types', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BackendAPIs.projectstypes')),
            ],
        ),
        migrations.AddField(
            model_name='projectcontent',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BackendAPIs.projectstypes'),
        ),
        migrations.CreateModel(
            name='HistoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('video_link', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_data', models.DateTimeField(auto_now=True)),
                ('history_type', models.CharField(choices=[('general', 'General'), ('history', 'History')], default='general', max_length=20)),
                ('image_field_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_image_1', to='BackendAPIs.imagelibrary')),
                ('image_field_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_image_2', to='BackendAPIs.imagelibrary')),
                ('image_field_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_image_3', to='BackendAPIs.imagelibrary')),
                ('image_field_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_image_4', to='BackendAPIs.imagelibrary')),
            ],
        ),
        migrations.AddField(
            model_name='content_gallery',
            name='image_field_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_image_1', to='BackendAPIs.imagelibrary'),
        ),
        migrations.AddField(
            model_name='content_gallery',
            name='image_field_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_image_10', to='BackendAPIs.imagelibrary'),
        ),
        migrations.AddField(
            model_name='content_gallery',
            name='image_field_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_image_11', to='BackendAPIs.imagelibrary'),
        ),
        migrations.AddField(
            model_name='content_gallery',
            name='image_field_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_image_12', to='BackendAPIs.imagelibrary'),
        ),
        migrations.AddField(
            model_name='content_gallery',
            name='image_field_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_image_2', to='BackendAPIs.imagelibrary'),
        ),
        migrations.AddField(
            model_name='content_gallery',
            name='image_field_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_image_3', to='BackendAPIs.imagelibrary'),
        ),
        migrations.AddField(
            model_name='content_gallery',
            name='image_field_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_image_4', to='BackendAPIs.imagelibrary'),
        ),
        migrations.AddField(
            model_name='content_gallery',
            name='image_field_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_image_5', to='BackendAPIs.imagelibrary'),
        ),
        migrations.AddField(
            model_name='content_gallery',
            name='image_field_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_image_6', to='BackendAPIs.imagelibrary'),
        ),
        migrations.AddField(
            model_name='content_gallery',
            name='image_field_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_image_7', to='BackendAPIs.imagelibrary'),
        ),
        migrations.AddField(
            model_name='content_gallery',
            name='image_field_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_image_8', to='BackendAPIs.imagelibrary'),
        ),
        migrations.AddField(
            model_name='content_gallery',
            name='image_field_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_image_9', to='BackendAPIs.imagelibrary'),
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('content_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BackendAPIs.content_gallery')),
                ('historycontent_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_historycontent_1', to='BackendAPIs.historycontent')),
                ('historycontent_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_historycontent_2', to='BackendAPIs.historycontent')),
                ('historycontent_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_historycontent_3', to='BackendAPIs.historycontent')),
                ('image_field_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_image_1', to='BackendAPIs.imagelibrary')),
                ('image_field_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_image_2', to='BackendAPIs.imagelibrary')),
                ('image_field_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_image_3', to='BackendAPIs.imagelibrary')),
                ('image_field_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_image_4', to='BackendAPIs.imagelibrary')),
                ('image_field_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_image_5', to='BackendAPIs.imagelibrary')),
                ('image_field_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_image_6', to='BackendAPIs.imagelibrary')),
                ('image_field_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_image_7', to='BackendAPIs.imagelibrary')),
                ('image_field_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_image_8', to='BackendAPIs.imagelibrary')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('embedded_link', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BackendAPIs.category')),
                ('image_field_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogpost_image_1', to='BackendAPIs.imagelibrary')),
                ('image_field_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogpost_image_2', to='BackendAPIs.imagelibrary')),
                ('image_field_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogpost_image_3', to='BackendAPIs.imagelibrary')),
                ('image_field_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogpost_image_4', to='BackendAPIs.imagelibrary')),
                ('image_field_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogpost_image_5', to='BackendAPIs.imagelibrary')),
                ('image_field_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogpost_image_6', to='BackendAPIs.imagelibrary')),
                ('image_field_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogpost_image_7', to='BackendAPIs.imagelibrary')),
                ('image_field_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogpost_image_8', to='BackendAPIs.imagelibrary')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
                'unique_together': {('title', 'slug')},
            },
        ),
    ]
